spring:
  application:
    name: notification-service
  cloud:
    stream:
      bindings:
        notificationEventSupplier-in-0:
          destination: notification-events
          group: notification-events-group
          binder: local_rabbit
          consumer:
            maxAttempts: 1
            retryableExceptions:
            concurrency:

      rabbit:
        bindings:
          notificationEventSupplier-in-0:
            consumer:
              republishToDlq: true
              autoBindDlq: true
#              requeueRejected: true
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
  sleuth:
    integration:
      enabled: true



server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
